### ISSUE TITLE
appsettings.secrets.json泄漏风险

### ISSUE THREAD

**Issue by hushenghao** [rwecho/V2ex.Maui#20]
这个文件包含AppCenter密钥，作为发布应用，此内容不要包含在版本控制中

**Comment by rwecho** [comment]
好的

**Comment by rwecho** [comment]
已经把这个变量转移到 secret 中

没有找到可以更换secret的地方, 或者需要重新删除这个app, 再创建(AppCenter)  如果需要可以考虑这样做. 
https://github.com/microsoft/appcenter/issues/2582
